/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdea0",
        "outline-variant": "#c4c6cf",
        "inverse-surface": "#2a303d",
        "on-secondary-container": "#775800",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#ecf0ff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "on-primary-container": "#778db2",
        secondary: "#795902",
        "inverse-primary": "#b1c7f0",
        tertiary: "#170e00",
        "on-background": "#161c27",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#314769",
        "secondary-fixed-dim": "#ebc166",
        "on-tertiary-fixed-variant": "#5c4300",
        "secondary-fixed": "#ffdf9e",
        "surface-container-highest": "#dde2f3",
        background: "#f9f9ff",
        "surface-tint": "#495f82",
        "primary-fixed-dim": "#b1c7f0",
        surface: "#f9f9ff",
        "surface-container-high": "#e3e8f9",
        primary: "#001026",
        "primary-container": "#0b2545",
        "on-tertiary-fixed": "#261900",
        "on-secondary-fixed": "#261a00",
        "surface-bright": "#f9f9ff",
        "tertiary-fixed-dim": "#eac16d",
        "on-secondary-fixed-variant": "#5b4300",
        "surface-dim": "#d4daea",
        outline: "#74777f",
        "primary-fixed": "#d5e3ff",
        "tertiary-container": "#312200",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-variant": "#dde2f3",
        "on-surface": "#161c27",
        "secondary-container": "#fdd275",
        "on-tertiary-container": "#aa8639",
        "surface-container": "#e8eeff",
        "on-surface-variant": "#44474e",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001c3b",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "gutter-mobile": "1rem",
        "gutter-tablet": "1.5rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "margin-mobile": "1rem",
        "space-2xs": "0.125rem",
        "margin-desktop": "4rem",
        "space-4xl": "6rem",
        "space-3xl": "4.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2rem",
        "margin-tablet": "2.5rem",
        "gutter-desktop": "2rem",
        "space-2xl": "3rem",
        "max-width-content": "1360px",
      },
      fontFamily: {
        "label-sm": ['"Source Sans 3"'],
        "display-lg-mobile": ["Merriweather"],
        "body-md": ['"Source Sans 3"'],
        "label-md": ['"Source Sans 3"'],
        "body-sm": ['"Source Sans 3"'],
        "body-lg": ['"Source Sans 3"'],
        "headline-lg": ["Merriweather"],
        "label-lg": ['"Source Sans 3"'],
        "headline-xl-mobile": ["Merriweather"],
        "display-lg": ["Merriweather"],
        "headline-md": ["Merriweather"],
        "legal-caption": ['"Source Sans 3"'],
        "headline-sm": ["Merriweather"],
        "headline-xl": ["Merriweather"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-xl-mobile": ["26px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "32px", fontWeight: "400" }],
        "legal-caption": ["11px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "700" }],
        "headline-xl": ["36px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "400" }],
      },
    },
  },
};
